### ISSUE TITLE
Cannot compile with coredns v1.2.5

### ISSUE THREAD

**Issue by ffilippopoulos** [coredns/kubernetai#14]
Tried to compile with the latest coredns version (v1.2.5) and give the following error:
```
# github.com/coredns/kubernetai/plugin/kubernetai
../kubernetai/plugin/kubernetai/kubernetai.go:70:9: assignment mismatch: 2 variables but 1 values
```
The coredns PR that introduces the change is: https://github.com/coredns/coredns/pull/2225

**Comment by ffilippopoulos** [comment]
sorry, I don't follow. This is just to report that by getting the latest coredns code go compiler complains about this: https://github.com/coredns/kubernetai/blob/c8e14a7446437414293b72ecf7d387fc098ec9eb/plugin/kubernetai/kubernetai.go#L70 line because `Scrub()` returns a single value.

**Comment by miekg** [comment]
Wrong issue.

**Comment by miekg** [comment]
Yeah, sorry replied to the wrong issue. Scrub can be deleted here, because
the server does this now.
