### ISSUE TITLE
Error during parsing: Unknown directive 'kubernetai'

### ISSUE THREAD

**Issue by bjethwan** [coredns/kubernetai#22]
I got this error when I replaced kubernetes with kubernetai in coredns configmap in my k8s cluster.
```
ks edit cm coredns
apiVersion: v1
data:
  Corefile: |-
    .:53 {
        errors
        health
        kubernetai cluster.local. in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
```
```
Error during parsing: Unknown directive 'kubernetai'
```
```
ks get pods
NAME                                                                  READY   STATUS             RESTARTS   AGE
coredns-784bfc9fbd-9f7sz                                              0/1     CrashLoopBackOff   3          1m
coredns-784bfc9fbd-svw98                                              0/1     CrashLoopBackOff   3          1m
dns-controller-7c49b9b6d5-6ljlz                                       1/1     Running            0          41m
```

**Comment by chrisohaver** [comment]
Kubernetai is an _external_ plugin, which means it's not compiled into the coredns image by default.
You'll need to compile a custom image of coredns, and us that in your cluster.

**Comment by chrisohaver** [comment]
I just now added a [section](https://github.com/coredns/kubernetai/blob/master/README.md#external-plugin) to the README for this.

**Comment by chrisohaver** [comment]
@bjethwan, BTW, thanks for these questions - it's helping improve the README.

**Comment by bjethwan** [comment]
Hi @chrisohaver 
It looks like a daunting task. But I am going to try for sure.
If you got an image hosted in some public container repo, which I can use for quick feature trail sake?

-Thanks

**Comment by chrisohaver** [comment]
I went ahead and built one for you ... should be at `chrisohaver/coredns:1.4.0-6f5b294-kubernetai`

**Comment by bjethwan** [comment]
Thank you @chrisohaver

**Comment by bjethwan** [comment]
Hi @chrisohaver 

Stage-1
Error during parsing: Unknown directive 'kubernetes'
This was easy as I changed kubernetes to kubernetai in coredns configmap.

Stage-2
/etc/coredns/Corefile:8 - Error during parsing: Unknown directive 'proxy'
For this I had to take out the proxy directive given in Corefile. I am not sure what might be the issue, as I am new to CoreDNS

Stage-3
It's working (success logs below). But I am not sure how to get to the IP which you mentioned in the sample given in the README.
I remember that you mentioned that it has to be kubenetes api server, so I am going to try it now.
 

Success logs 
$ ks logs coredns-6bfbd7466d-4bms7
.:53
2019-04-05T22:26:44.507Z [INFO] plugin/reload: Running configuration MD5 = 22a50a003acc4773218243b829075bef
2019-04-05T22:26:44.508Z [INFO] CoreDNS-1.4.0-6f5b294-kubernetai
2019-04-05T22:26:44.508Z [INFO] linux/amd64, go1.12, 6f5b294d-dirty
CoreDNS-1.4.0-6f5b294-kubernetai
linux/amd64, go1.12, 6f5b294d-dirty
2019-04-05T22:26:44.508Z [ERROR] plugin/errors: 2 6862275574548763958.7746989624812777262. HINFO: plugin/loop: no next plugin found

**Comment by chrisohaver** [comment]
Instead of removing `proxy`, you'll need to replace it with `forward`.  If you don't, you wont be able to resolve any names that are not in your cluster zone. This is also why you see the error in the log. The `proxy` plugin is no longer supported in  the master branch.  It has been replaced with the `forward` plugin. 

For the IP address, it depends on how the cluster is set up, but try the IP of the master node on port 6443.

**Comment by bjethwan** [comment]
Hi @chrisohaver 

I ran into below error.
```
Error: plugin/kubernetai: failed to create kubernetes notification controller: "tls: failed to find any PEM data in certificate input"
```
I tried your coredns image today.
chrisohaver/coredns:1.4.0-6f5b294-kubernetai

And followed below steps
I extracted the client-cert, client-key and ca-cert from my kubeconfig for remote cluster.
Then base64 decoded those strings.
Then added those in coredns configmap (including the header and footer)
Then updated the coredns deployment.
(ks is alias for 'kubectl -n kube-system')

```
$ ks edit deploy coredns
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: Corefile
            path: Corefile
          - key: ca.crt
            path: ca.crt
          - key: client.crt
            path: client.crt
          - key: client.key
            path: client.key
          name: coredns
        name: config-volume

$ ks edit cm coredns
        ...
        kubernetai cluster.local. {
          fallthrough
        }
        kubernetai cluster.local {
          endpoint https://api.c2.ap-south-1.bj-cloud.info
          tls /etc/coredns/client.crt /etc/coredns/client.key /etc/coredns/ca.crt
        }
       ...
  ca.crt: |
    -----BEGIN CERTIFICATE----- <removed> -----END CERTIFICATE-----
  client.crt: |
    -----BEGIN CERTIFICATE----- <removed> -----END CERTIFICATE-----
  client.key: |
    -----BEGIN RSA PRIVATE KEY----- <removed> -----END RSA PRIVATE KEY-----
```
Stage-1
plugin/kubernetai: invalid configuration: [unable to read client-cert client.crt for  due to open client.crt: no such file or directory, unable to read client-key client.key for  due to open client.key: no such file or directory, unable to read certificate-authority ca.crt for  due to open ca.crt: no such file or directory]

Stage-2 (I added all the keys and certs in coredns cm itself - pls check the file atatched)
plugin/kubernetai: failed to create kubernetes notification controller: "tls: failed to find any PEM data in certificate input"

**Comment by bjethwan** [comment]
I missed to attach the file...doing it now

[yaml.zip](https://github.com/coredns/kubernetai/files/3050234/yaml.zip)

**Comment by bjethwan** [comment]
Hi @chrisohaver ,
Kindly give me some hints to move forward. BTW, I bring up k8s clusters using kops, so I used the public kuber api server endpoint from my kubeconfig file.

Please let me know if you need any further details.

-Thanks

**Comment by bjethwan** [comment]
> 
> 
> Instead of removing `proxy`, you'll need to replace it with `forward`. If you don't, you wont be able to resolve any names that are not in your cluster zone. This is also why you see the error in the log. The `proxy` plugin is no longer supported in the master branch. It has been replaced with the `forward` plugin.
> 
> For the IP address, it depends on how the cluster is set up, but try the IP of the master node on port 6443.

Hi @chrisohaver ,
Thanks for letting me know about proxy and forward. But unfortunately, I couldn't make it to work.

```
  Corefile: |-
    .:53 {
        log
        errors
        health
        kubernetai cluster.local. {
          fallthrough
        }
        prometheus :9153
        forward . /etc/resolv.conf
        loop
        cache 30
        loadbalance
        reload
    }
```
Errors
```
2019-04-06T20:18:43.164Z [INFO] 100.96.1.17:33658 - 20883 "A IN google.com.default.svc.cluster.local. udp 54 false 512" NOERROR - 0 0.000083576s
2019-04-06T20:18:43.164Z [ERROR] plugin/errors: 2 google.com.default.svc.cluster.local. A: plugin/kubernetes: no next plugin found
```

**Comment by bjethwan** [comment]
Hi @chrisohaver 

I got remote cluster dns discovery part working. However, the forward plugin is still not working.

I am trying to make "remote dns" work for my usecase. 
I would like to show you complete setup once I get this working.

And I would definitely like to give you a hand in documenting the steps.
So that it's easy for others to quickly start using it.

-Thanks

**Comment by chrisohaver** [comment]
Your Corefile only has one kubernetai stanza, and it has a fallthrough, which should fall through to the next kubernetai connection, but it's not there. For it to work properly,  you need two kubernetai stanzas.  For example...

```
  Corefile: |-
    .:53 {
        log
        errors
        health
        kubernetai cluster.local. {
          fallthrough
        }
        kubernetai cluster.local {
          endpoint https://api.c2.ap-south-1.bj-cloud.info
          tls /etc/coredns/client.crt /etc/coredns/client.key /etc/coredns/ca.crt
        }
        prometheus :9153
        forward . /etc/resolv.conf
        loop
        cache 30
        loadbalance
        reload
    }
```

**Comment by chrisohaver** [comment]
In response to the cross-posted issue #2768 ...

> proxy doesn't work as I was using latest 1.4 version

You are using an unreleased compilation of coredns/coredns master at 6f5b294, not the latest 1.4 ... it was a custom compile I made for you.

>Although I am showing the corefile with autopath, but it didn't work when I was not using autopath.
> And "autopath @kubernetai" completely breaks the system.

I would leave `autopath` out of the equation for now.  `autopath @kubernetes` is expected, and should work, but I think there are some confusing caveats. So, IMO best to leave that out for now.  One step at a time.  Let's get it working _without_ autopath first.

Your final `kubernetai` should not have a `fallthrough`.  The would result in sending unresolved `cluster.local.` queries to your upstream servers, which probably isn't what you want to do.  That said, you should be allowed to configure it to fallthrough to upstream, even if it doesn't make sense, so there may be a corner case bug there.

> Should I separate out the domains (cluster.local and .)?

No, that should not be necessary.  You can, but it shouldn't make any difference here. 

How does the following config work?

```
  Corefile: |-
    .:53 {
        log
        errors
        health
        kubernetai cluster.local. {
          pods insecure
          fallthrough
        }
        kubernetai cluster.local. {
          pods insecure
          endpoint https://remote-k8s-api-server
          tls /etc/bipin/client.crt /etc/bipin/client.key /etc/bipin/ca.crt
        }
        forward . /etc/resolv.conf
        loop
        cache 30
        loadbalance
        reload
    }
```

**Comment by chrisohaver** [comment]
reopen if this is still an issue

**Comment by chaudharyalka** [comment]
> Hi @chrisohaver
> 
> I ran into below error.
> 
> ```
> Error: plugin/kubernetai: failed to create kubernetes notification controller: "tls: failed to find any PEM data in certificate input"
> ```
> 
> I tried your coredns image today.
> chrisohaver/coredns:1.4.0-6f5b294-kubernetai
> 
> And followed below steps
> I extracted the client-cert, client-key and ca-cert from my kubeconfig for remote cluster.
> Then base64 decoded those strings.
> Then added those in coredns configmap (including the header and footer)
> Then updated the coredns deployment.
> (ks is alias for 'kubectl -n kube-system')
> 
> ```
> $ ks edit deploy coredns
>       volumes:
>       - configMap:
>           defaultMode: 420
>           items:
>           - key: Corefile
>             path: Corefile
>           - key: ca.crt
>             path: ca.crt
>           - key: client.crt
>             path: client.crt
>           - key: client.key
>             path: client.key
>           name: coredns
>         name: config-volume
> 
> $ ks edit cm coredns
>         ...
>         kubernetai cluster.local. {
>           fallthrough
>         }
>         kubernetai cluster.local {
>           endpoint https://api.c2.ap-south-1.bj-cloud.info
>           tls /etc/coredns/client.crt /etc/coredns/client.key /etc/coredns/ca.crt
>         }
>        ...
>   ca.crt: |
>     -----BEGIN CERTIFICATE----- <removed> -----END CERTIFICATE-----
>   client.crt: |
>     -----BEGIN CERTIFICATE----- <removed> -----END CERTIFICATE-----
>   client.key: |
>     -----BEGIN RSA PRIVATE KEY----- <removed> -----END RSA PRIVATE KEY-----
> ```
> 
> Stage-1
> plugin/kubernetai: invalid configuration: [unable to read client-cert client.crt for due to open client.crt: no such file or directory, unable to read client-key client.key for due to open client.key: no such file or directory, unable to read certificate-authority ca.crt for due to open ca.crt: no such file or directory]
> 
> Stage-2 (I added all the keys and certs in coredns cm itself - pls check the file atatched)
> plugin/kubernetai: failed to create kubernetes notification controller: "tls: failed to find any PEM data in certificate input"

Hey @bjethwan i am getting the same error as mentioned in stage-1 when i tried mapping client certs from host. Kindly give me some hint to resolve this.
