### ISSUE TITLE
Unable to build coredns image with kubernetai

### ISSUE THREAD

**Issue by bjethwan** [coredns/kubernetai#24]
I was following the steps given in the readme file.
Last time Chris gave me a docker image to test but I got to build one with CoreDNS 1.3.1.
However, as the starter I thought of trying the steps for CoreDNS 1.4.0

gist:

cannot find package "github.com/coredns/coredns/core/plugin
cannot find package "github.com/coredns/coredns/coremain

details:

```
> git clone https://github.com/coredns/coredns
> cd coredns	
> git checkout tags/v1.4.0 -b 1.4.0
make -f Makefile.release DOCKER=bjethwan/coredns:1.4.0-kubernetai release
go get github.com/estesp/manifest-tool
Cleaning old builds
Building: darwin/amd64 - 1.4.0
mkdir -p build/darwin/amd64 && /Library/Developer/CommandLineTools/usr/bin/make coredns BINARY=build/darwin/amd64/coredns SYSTEM="GOOS=darwin GOARCH=amd64" CHECKS="godeps" BUILDOPTS=""
(cd /Users/bj151v/go/src/github.com/mholt/caddy 2>/dev/null              && git checkout -q master 2>/dev/null || true)
(cd /Users/bj151v/go/src/github.com/miekg/dns 2>/dev/null                && git checkout -q master 2>/dev/null || true)
(cd /Users/bj151v/go/src/github.com/prometheus/client_golang 2>/dev/null && git checkout -q master 2>/dev/null || true)
go get -u github.com/mholt/caddy
go get -u github.com/miekg/dns
go get -u github.com/prometheus/client_golang/prometheus/promhttp
go get -u github.com/prometheus/client_golang/prometheus
(cd /Users/bj151v/go/src/github.com/mholt/caddy              && git checkout -q v0.11.4)
(cd /Users/bj151v/go/src/github.com/miekg/dns                && git checkout -q v1.1.4)
(cd /Users/bj151v/go/src/github.com/prometheus/client_golang && git checkout -q v0.9.1)
CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build  -ldflags="-s -w -X github.com/coredns/coredns/coremain.GitCommit=8dcc7fcc" -o build/darwin/amd64/coredns
coredns.go:9:2: cannot find package "github.com/coredns/coredns/core/plugin" in any of:
	/usr/local/Cellar/go/1.12.6/libexec/src/github.com/coredns/coredns/core/plugin (from $GOROOT)
	/Users/bj151v/go/src/github.com/coredns/coredns/core/plugin (from $GOPATH)
coredns.go:6:2: cannot find package "github.com/coredns/coredns/coremain" in any of:
	/usr/local/Cellar/go/1.12.6/libexec/src/github.com/coredns/coredns/coremain (from $GOROOT)
	/Users/bj151v/go/src/github.com/coredns/coredns/coremain (from $GOPATH)
make[1]: *** [coredns] Error 1
make: *** [build] Error 2
```

**Comment by chrisohaver** [comment]
Did you clone CoreDNS into your go path tree? ... `/Users/bj151v/go/src/github.com/coredns/coredns`

**Comment by bjethwan** [comment]
Hi @chrisohaver , Thank you...I was doing this for first time.

I got struck at the last command now.

cd $GOPATH
go get -d github.com/coredns/coredns
cd src/github.com/coredns/coredns/
git checkout tags/v1.4.0
make -f Makefile.release DOCKER=<<docker account/username>> release
make -f Makefile.release DOCKER=<<docker account/username>> docker
>>>IT IS FINE TILL HERE

export DOCKER_LOGIN=<<username>>
export DOCKER_PASSWORD=<<password>>
make -f Makefile.release DOCKER=bjethwan docker-push
>>>ERROR
manifest-tool push from-args --platforms linux/amd64,linux/arm,linux/arm64,linux/ppc64le,linux/s390x --template bjethwan/coredns:coredns-ARCH --target bjethwan/coredns:1.4.0
FATA[0033] Registry push unsuccessful: response 401: 401 Unauthorized 
make: *** [docker-push] Error 1

**Comment by bjethwan** [comment]
I got the same issue for CoreDNS 1.5.0 branch 

Pushing: 1.5.0 to bjethwan/coredns
for arch in amd64 arm arm64 ppc64le s390x; do \
	    docker push bjethwan/coredns:coredns-$arch ;\
	done
The push refers to repository [docker.io/bjethwan/coredns]
16aa14272569: Pushed 
c0eb2ea97388: Layer already exists 
coredns-amd64: digest: sha256:f7f71266426cd81eb79f81b8ea70c5e0a054aecbc0da8fd3f48961d29246aff5 size: 739
The push refers to repository [docker.io/bjethwan/coredns]
878b94cdad36: Pushed 
c0eb2ea97388: Layer already exists 
coredns-arm: digest: sha256:9d34b21cac38aa78772680ea16364e645e90349cf8e095c493d00c3ce907975f size: 739
The push refers to repository [docker.io/bjethwan/coredns]
4e69d4ec8e47: Pushed 
c0eb2ea97388: Layer already exists 
coredns-arm64: digest: sha256:ad687b300c70095094efb3be73cdfa02db97f20ef9c32394349c951d8275276f size: 739
The push refers to repository [docker.io/bjethwan/coredns]
1625db076d9a: Pushed 
c0eb2ea97388: Layer already exists 
coredns-ppc64le: digest: sha256:9ab23ee3d6089045356cf7c2611e03d14829dcbaaf7b14e5b250ac76e8e0e980 size: 739
The push refers to repository [docker.io/bjethwan/coredns]
761e22a3d2cd: Pushed 
c0eb2ea97388: Layer already exists 
coredns-s390x: digest: sha256:6d7fe8aada641010be72949e5c196f101463b99747f57a2d2524085e2af29ec3 size: 739
manifest-tool push from-args --platforms linux/amd64,linux/arm,linux/arm64,linux/ppc64le,linux/s390x --template bjethwan/coredns:coredns-ARCH --target bjethwan/coredns:1.5.0
FATA[0034] Registry push unsuccessful: response 401: 401 Unauthorized 
make: *** [docker-push] Error 1

**Comment by bjethwan** [comment]
Hi @chrisohaver 

I upgraded docker on my mac, which I am using to CoreDNS image with Kubernetai included, but still I couldn't get it to work.

$ docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false


manifest-tool push from-args --platforms linux/amd64,linux/arm,linux/arm64,linux/ppc64le,linux/s390x --template bjethwan/coredns:coredns-ARCH --target bjethwan/coredns:1.5.0
FATA[0052] Registry push unsuccessful: response 401: 401 Unauthorized 
make: *** [docker-push] Error 1

**Comment by bjethwan** [comment]
I tried below as suggested on https://gitlab.com/gitlab-org/gitlab-ce/issues/40197
mkdir -p ~/.docker
echo '{"experimental": "enabled"}' > ~/.docker/config.json

But I got the same error as above.

I am going to try quay.io next

**Comment by bjethwan** [comment]
The last step with manifest-tool failed again, with a little different error message.

$ docker login quay.io
Username: bjethwan
Password: 
Login Succeeded
INHYIMAC013:coredns bj151v$ make -f Makefile.release DOCKER=quay.io/bjethwan docker-push
Login Succeeded
Pushing: 1.5.0 to quay.io/bjethwan/coredns
for arch in amd64 arm arm64 ppc64le s390x; do \
	    docker push quay.io/bjethwan/coredns:coredns-$arch ;\
	done
The push refers to repository [quay.io/bjethwan/coredns]
16aa14272569: Pushed 
c0eb2ea97388: Pushed 
coredns-amd64: digest: sha256:f4dbc5b9f6112dfd78dc578a2add8de0e6777ce3c79695ee68d99a0eca62b982 size: 3184
The push refers to repository [quay.io/bjethwan/coredns]
878b94cdad36: Pushed 
c0eb2ea97388: Layer already exists 
coredns-arm: digest: sha256:e45c4844407e67e445995274c06af1aaaaaf8953f758a0be822e2b9aaf1c7e78 size: 3183
The push refers to repository [quay.io/bjethwan/coredns]
4e69d4ec8e47: Pushed 
c0eb2ea97388: Layer already exists 
coredns-arm64: digest: sha256:55b8483ebd8e06d39b3fddf122d56517140d7393e2c187639170767f465323fe size: 3185
The push refers to repository [quay.io/bjethwan/coredns]
1625db076d9a: Pushed 
c0eb2ea97388: Layer already exists 
coredns-ppc64le: digest: sha256:d94c39dd037458cde929dd81141c8968b2c5f401884ae8b397357321dfa80b51 size: 3187
The push refers to repository [quay.io/bjethwan/coredns]
761e22a3d2cd: Pushed 
c0eb2ea97388: Layer already exists 
coredns-s390x: digest: sha256:cf49730133f194ede38d653936917ee7acb2b23933758cd6f287835009605730 size: 3183
manifest-tool push from-args --platforms linux/amd64,linux/arm,linux/arm64,linux/ppc64le,linux/s390x --template quay.io/bjethwan/coredns:coredns-ARCH --target quay.io/bjethwan/coredns:1.5.0
FATA[0040] Registry push unsuccessful: response 415: 415 UNSUPPORTED MEDIA TYPE 
make: *** [docker-push] Error 1

**Comment by bjethwan** [comment]
Hi @chrisohaver ,

I got it working. 

It was stupid on my part that I didn't verify $HOME/.docker/config.json.

On my mac it was trying to use keychain and it was set with  "credsStore": "osxkeychain".

Once I set the credentials manually and deleted  "credsStore": "osxkeychain".
manifest-tool started working.

-Thanks

**Comment by bjethwan** [comment]
Hi @chrisohaver ,

I am struck again.
I followed the given steps exactly (plugin.cfg update)
But then it complained "/etc/coredns/Corefile:11 - Error during parsing: Unknown directive 'kubernetai'"

I check the plugin.cfg again and it said that I need to run "go gen & go build".

$ go generate
$ go build
../../../gopkg.in/DataDog/dd-trace-go.v0/opentracing/span.go:7:2: cannot find package "github.com/DataDog/dd-trace-go/tracer" in any of:
	/Users/bj151v/go/src/gopkg.in/DataDog/dd-trace-go.v0/vendor/github.com/DataDog/dd-trace-go/tracer (vendor tree)
	/usr/local/go/src/github.com/DataDog/dd-trace-go/tracer (from $GOROOT)
	/Users/bj151v/go/src/github.com/DataDog/dd-trace-go/tracer (from $GOPATH)
core/plugin/zplugin.go:44:2: cannot find package "kubernetai" in any of:
	/usr/local/go/src/kubernetai (from $GOROOT)
	/Users/bj151v/go/src/kubernetai (from $GOPATH)

$ go get github.com/coredns/kubernetai
package github.com/DataDog/dd-trace-go/tracer: cannot find package "github.com/DataDog/dd-trace-go/tracer" in any of:
	/usr/local/go/src/github.com/DataDog/dd-trace-go/tracer (from $GOROOT)
	/Users/bj151v/go/src/github.com/DataDog/dd-trace-go/tracer (from $GOPATH)
package kubernetai: unrecognized import path "kubernetai" (import path does not begin with hostname)


![image](https://user-images.githubusercontent.com/5045325/60803184-44a0ca80-a198-11e9-918c-1e29a245e02e.png)


Kindly give me some hints to fix this build issue.

**Comment by chrisohaver** [comment]
What does your `plugin.cfg` look like.

**Comment by bjethwan** [comment]
Hi @chrisohaver ,

It's like below image. And the file is attached too.

![image](https://user-images.githubusercontent.com/5045325/60821276-db817d00-a1c0-11e9-90e4-3c23090351b5.png)

[plugin.cfg.zip](https://github.com/coredns/kubernetai/files/3369030/plugin.cfg.zip)

-Thanks

**Comment by chrisohaver** [comment]
The path is not correct.  kubernetai is an external plugin, so you need to specify the path... e.g. 

```
kubernetai:github.com/coredns/kubernetai
```

**Comment by bjethwan** [comment]
Hi @chrisohaver 

I ran into another issue:
core/plugin/zplugin.go:43:2: import "github.com/coredns/kubernetai" is a program, not an importable package

I attempted it a few times with below options in plugin.cfg
And between each run, I ran the make with clean target.

kubernetai:kubernetai
kubernetai:github.com/kubernetai
kubernetai:github.com/kubernetai/plugin/kubernetai


DETAILS
---------
$ export GO111MODULE=on

$ go get github.com/coredns/kubernetai
go: finding github.com/coredns/kubernetai latest
go: downloading github.com/DataDog/zstd v1.3.5
go: extracting github.com/DataDog/zstd v1.3.5
import cycle not allowed
package github.com/coredns/kubernetai
	imports github.com/coredns/coredns/core/plugin
	imports github.com/coredns/kubernetai

$ make -f Makefile.release DOCKER=bjethwan release
GO111MODULE=off go get github.com/estesp/manifest-tool
Cleaning old builds
Building: darwin/amd64 - 1.5.0-kubernetai
mkdir -p build/darwin/amd64 && /Library/Developer/CommandLineTools/usr/bin/make coredns BINARY=build/darwin/amd64/coredns SYSTEM="GOOS=darwin GOARCH=amd64" CHECKS="" BUILDOPTS=""
GO111MODULE=on CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build  -ldflags="-s -w -X github.com/coredns/coredns/coremain.GitCommit=e3f9a80b-dirty" -o build/darwin/amd64/coredns
import cycle not allowed
package github.com/coredns/coredns
	imports github.com/coredns/coredns/core/plugin
	imports github.com/coredns/kubernetai
	imports github.com/coredns/coredns/core/plugin
core/plugin/zplugin.go:43:2: import "github.com/coredns/kubernetai" is a program, not an importable package
make[1]: *** [coredns] Error 1
make: *** [build] Error 2

$ go generate
$ go build
import cycle not allowed
package github.com/coredns/coredns
	imports github.com/coredns/coredns/core/plugin
	imports github.com/coredns/kubernetai
	imports github.com/coredns/coredns/core/plugin
core/plugin/zplugin.go:43:2: import "github.com/coredns/kubernetai" is a program, not an importable package

**Comment by chrisohaver** [comment]
IIRC, it has to be the full path to the plugin relative to the go src dir ...  the example in my above comment was incomplete ... should be something like...

```
kubernetai:github.com/coredns/kubernetai/plugin/kubernetai
```

**Comment by bjethwan** [comment]
Hi @chrisohaver 

It works !!!

Thank you Chris !

I accept my mistake for missing /coredns in plugin.cfg.
