### ISSUE TITLE
Unable to configure ignoring SERVFAIL

### ISSUE THREAD

**Issue by benclarkwood** [coredns/kubernetai#26]
Hey folks!

First off, thanks for having already solved the issue of wanting to serve multiple Kubernetes clusters with a single coredns (very handy for integrating Kubernetes's DNS into our existing DNS infra).

One problem we have is that due to *waves hands* reasons, the kubelets of a cluster have non-contiguous CIDRs, but a _set_ of clusters have a large contiguous block.

So our config looks something like:

```
kubernetai <cluster zone> 10.0.0.0/16
...
kubernetai <cluster zone> 10.0.0.0/16
```

This always works fine for forward DNS, but if any cluster is down, then it breaks reverse dns for any clusters after it.

Would an additional flag (e.g. ignore_servfail) be an acceptable solution to ya'll? As we're essentially using kubernetai to express an authoritative whole, and so we need each cluster to be consulted before declaring SERVFAIL.

**Comment by johnbelamaric** [comment]
Currently `fallthrough` is done on NXDOMAIN. Perhaps we need to do it for SERVFAIL in kubernetai, though I haven't thought through all the implications of that.

**Comment by benclarkwood** [comment]
I think it would make sense as opt-in behavior given that for many folks, they'd just have a series of kubernetai directives with no overlap for forward or reverse so it would be wasteful to fallthrough.

I'd be happy to put up a patch for a flag?

**Comment by johnbelamaric** [comment]
What do you think the config would look like? Because right now I believe it just uses the `kubernertes`  config, you can't easily customize just for `kubernetai`.

**Comment by benclarkwood** [comment]
Ah, yep, I was forgetting that small detail 🤦‍♂

**Comment by chrisohaver** [comment]
> Perhaps we need to do it for SERVFAIL in kubernetai, though I haven't thought through all the implications of that.

Thinking on this a bit, IMO it makes sense to fall through when the API is down too, _except for the last kubernetai in the list_.  However, SERVFAIL could be potentially returned for reasons other than a downed API connection.  We could instead check `APIconn.HasSynced()`, and then fall through immediately to the next kubernetai if is is not synced.

**Comment by benclarkwood** [comment]
Cool, @chrisohaver, I will take a swing at that and report back.

**Comment by benclarkwood** [comment]
@chrisohaver finally got this done: https://github.com/coredns/kubernetai/pull/29
