### ISSUE TITLE
How can I become a project contributor for CoreDNS?

### ISSUE THREAD

**Issue by bjethwan** [coredns/kubernetai#31]
@chrisohaver 

Hi Chris,
I wish to become a project contributor for CoreDNS and I can start with CoreDNS/Kubernetai plugin. 

Kindly let me know the process.

-Thanks

**Comment by chrisohaver** [comment]
Thanks!  Follow the guidelines here ... https://github.com/coredns/coredns/blob/master/CONTRIBUTING.md

**Comment by bjethwan** [comment]
Hi Chris, I am dealing with sudden death in my family.
