### ISSUE TITLE
SERVFAIL on fallthrough to forward

### ISSUE THREAD

**Issue by t0rr3sp3dr0** [coredns/kubernetai#39]
When trying to use kubernetai with the following configuration

```
.:53 {
  errors

  kubernetai cluster-a.local in-addr.arpa ip6.arpa {
    fallthrough in-addr.arpa ip6.arpa
    kubeconfig /Users/user/.kube/config arn:aws:eks:us-east-1:000000000000:cluster/a
    pods insecure
  }

  kubernetai cluster-b.local in-addr.arpa ip6.arpa {
    fallthrough in-addr.arpa ip6.arpa
    kubeconfig /Users/user/.kube/config arn:aws:eks:us-east-1:000000000000:cluster/b
    pods insecure
  }

  forward . /etc/resolv.conf {
    max_concurrent 1000
  }
}
```

and using dig to query PTR records of an IP address

```bash
dig @127.0.0.1 -x 1.1.1.1
```

it raises an error saying that the next plugin was not found

```
.:53
CoreDNS-1.8.3
darwin/amd64, go1.16.3, 4293992b-dirty
[ERROR] plugin/errors: 2 1.1.1.1.in-addr.arpa. PTR: plugin/kubernetes: no next plugin found specified
```

and answers the request with SERVFAIL

```
; <<>> DiG 9.10.6 <<>> -x 1.1.1.1 @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 57076
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;1.1.1.1.in-addr.arpa.          IN      PTR

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu May 06 17:11:41 -03 2021
;; MSG SIZE  rcvd: 49
```

instead of using the forward plugin configuration.

**Comment by t0rr3sp3dr0** [comment]
I don't know if it would be appropriate, but patching https://github.com/coredns/kubernetai/blob/a3ae9db639d497b20fefa309d180571f4297cfde/plugin/kubernetai/kubernetai.go#L74-L76 to

```golang
		} else {
			k.Next = k8i.Next
			rcode, err = k.ServeDNS(ctx, w, r)
		}
```

solved my problem.

**Comment by chrisohaver** [comment]
Thanks @t0rr3sp3dr0!  At first glance, that seems like the right fix.

**Comment by t0rr3sp3dr0** [comment]
Actually, I can only set `Next` if `k8i.Fall[i].Through(state.Name())` is true. I'll submit a PR with the changes.

**Comment by chrisohaver** [comment]
OK. On second look - it probably would be better to set it at setup time.

**Comment by chrisohaver** [comment]
https://github.com/coredns/kubernetai/blob/a3ae9db639d497b20fefa309d180571f4297cfde/plugin/kubernetai/setup.go#L33-L36

In there, setting the last instance of `k8i.Kubernetes` to `next` ...

**Comment by t0rr3sp3dr0** [comment]
Instead of setting the `Next` for the last Kubernetes instance, I think it would be better to remove the condition that makes the fall zones of the last Kubernetes instance not nil. And then remove the specialization of the code that treats the last Kubernetes instance as a special one. This also make the code simpler.

So this piece of code https://github.com/coredns/kubernetai/blob/a3ae9db639d497b20fefa309d180571f4297cfde/plugin/kubernetai/setup.go#L60-L63 would become

```golang
		// for all instances, disable fallthrough in the Kubernetes object
		k8i.Kubernetes[i].Fall.Zones = nil
```

And https://github.com/coredns/kubernetai/blob/a3ae9db639d497b20fefa309d180571f4297cfde/plugin/kubernetai/kubernetai.go#L47-L78 would become

``` golang
		// If fallthrough is disabled, then we should not continue to the next plugin.
		if !k8i.Fall[i].Through(state.Name()) {
			return k.ServeDNS(ctx, w, r)
		}

		// Use a non-writer so we don't write NXDOMAIN to client
		nw := nonwriter.New(w)

		_, err := k.ServeDNS(ctx, nw, r)

		// Return SERVFAIL if error
		if err != nil {
			return dns.RcodeServerFailure, err
		}

		// If NXDOMAIN, continue to next kubernetes instead of next plugin
		if nw.Msg.Rcode == dns.RcodeNameError {
			continue
		}

		// Otherwise write message to client
		m := nw.Msg
		state.SizeAndDo(m)
		m = state.Scrub(m)
		w.WriteMsg(m)

		return m.Rcode, err
```

Because previously https://github.com/coredns/kubernetai/blob/a3ae9db639d497b20fefa309d180571f4297cfde/plugin/kubernetai/kubernetai.go#L80 was never called as the last Kubernets instance would throw an error as no `Next` was set.
