### ISSUE TITLE
Under syntax in README.md is a dead link

### ISSUE THREAD

**Issue by sdake** [coredns/kubernetai#9]
Just came across kubernetai and was taking a look.  The link in README.md is a dead link.  I'd submit a PR to fix the problem, but I'm not sure what the proper link should be.  I'd like to do an eval - so if someone could provide the proper link it would be appreciated.

Cheers
-steve

**Comment by johnbelamaric** [comment]
Proper link is: https://github.com/coredns/coredns/tree/master/plugin/kubernetes

On Mar 20, 2018, at 7:20 PM, Steven Dake <notifications@github.com<mailto:notifications@github.com>> wrote:


Just came across kubernetai and was taking a look. The link in README.md is a dead link. I'd submit a PR to fix the problem, but I'm not sure what the proper link should be. I'd like to do an eval - so if someone could provide the proper link it would be appreciated.

Cheers
-steve
